version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"  # Порт для контроллера
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"  # для доступа внутри Docker-сети
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    volumes:
      - ./kafka-data:/tmp/kraft-combined-logs
    healthcheck:
      test: 
        - "CMD"
        - "bash"
        - "-c"
        - |
          # Проверяем доступность брокера Kafka
          kafka-broker-api-versions.sh --bootstrap-server localhost:9092
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - ./MainService/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  main:
    image: main_service
    build:
      context: ./MainService
    ports:
    - "8081:8081"
    depends_on:
      - kafka
      - postgres

  DataProducer:
    image: data_producer
    build:
      context: ./DataProducer
    depends_on:
      - kafka
      - postgres