package main

import (
	. "DataProducer/models"
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/segmentio/kafka-go"
)

func main() {
	ctx := context.Background()

	orders := []Order{
		{
			OrderUID:        "b563feb7b2b84b6a1d8b4567",
			TrackNumber:     "WBILMTESTTRACK",
			Entry:           "WBIL",
			Locale:          "ru",
			CustomerID:      "cust_abcdefgh",
			DeliveryService: "meest",
			ShardKey:        "1",
			SmID:            80,
			DateCreated:     time.Date(2023, time.March, 15, 10, 30, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Иван Иванов",
				City:    "Москва",
				Address: "ул. Тверская, д. 1",
				Region:  "Московская область",
				Email:   "ivan@example.com",
				Phone:   "+79991234567",
				Zip:     "1234567",
			},
			Payment: Payment{
				Transaction:  "trans123456",
				Currency:     "RUB",
				Provider:     "sberpay",
				Amount:       1500,
				PaymentDT:    time.Now().Unix(),
				Bank:         "sberbank",
				DeliveryCost: 200,
				GoodsTotal:   1300,
			},
			Items: []Item{
				{
					ChrtID:      12345,
					TrackNumber: "ITEM-12345",
					Price:       500,
					Name:        "Книга",
					Sale:        0,
					Size:        "M",
					TotalPrice:  500,
					NmID:        98765,
					Brand:       "Издательство",
					Status:      200,
				},
			},
		},
		{
			OrderUID:        "order2_uid_abcde",
			TrackNumber:     "TRACK-XYZ-789",
			Entry:           "ENTRY2",
			Locale:          "uk",
			CustomerID:      "cust_zxcvbnm",
			DeliveryService: "cdelivery",
			ShardKey:        "2",
			SmID:            85,
			DateCreated:     time.Date(2023, 4, 10, 14, 20, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Анна Сидорова",
				City:    "Киев",
				Address: "пр. Победы, д. 10",
				Region:  "",
				Email:   "anna@example.com",
				Phone:   "+380991234567",
				Zip:     "7654321",
			},
			Payment: Payment{
				Transaction:  "trans654321",
				Currency:     "UAH",
				Provider:     "paypal",
				Amount:       2500,
				PaymentDT:    time.Now().Unix(),
				Bank:         "paypal_bank",
				DeliveryCost: 300,
				GoodsTotal:   2200,
			},
			Items: []Item{
				{
					ChrtID:      54321,
					TrackNumber: "ITEM-54321",
					Price:       1000,
					Name:        "Смартфон",
					Sale:        10,
					Size:        "L",
					TotalPrice:  990,
					NmID:        123456,
					Brand:       "BrandY",
					Status:      200,
				},
			},
		},
		// Новые заказы
		{
			OrderUID:        "min_order_333",
			TrackNumber:     "TRACK-333",
			Entry:           "WBIL",
			Locale:          "ru",
			CustomerID:      "cust_333",
			DeliveryService: "meest",
			ShardKey:        "3",
			SmID:            90,
			DateCreated:     time.Date(2023, 5, 12, 9, 15, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Петр Петров",
				City:    "Санкт-Петербург",
				Address: "Невский пр., д. 50",
				Region:  "Ленинградская область",
				Email:   "petr@example.com",
				Phone:   "+78121234567",
				Zip:     "190000",
			},
			Payment: Payment{
				Transaction:  "trans333333",
				Currency:     "RUB",
				Provider:     "yandexmoney",
				Amount:       5000,
				PaymentDT:    time.Now().Unix(),
				Bank:         "sberbank",
				DeliveryCost: 500,
				GoodsTotal:   4500,
			},
			Items: []Item{
				{
					ChrtID:      33301,
					TrackNumber: "ITEM-33301",
					Price:       1500,
					Name:        "Ноутбук",
					Sale:        5,
					Size:        "XL",
					TotalPrice:  1425,
					NmID:        333001,
					Brand:       "BrandZ",
					Status:      200,
				},
				{
					ChrtID:      33302,
					TrackNumber: "ITEM-33302",
					Price:       500,
					Name:        "Мышь",
					Sale:        0,
					Size:        "S",
					TotalPrice:  500,
					NmID:        333002,
					Brand:       "BrandM",
					Status:      200,
				},
			},
		},
		{
			OrderUID:        "order_444_uk",
			TrackNumber:     "TRACK-444-UA",
			Entry:           "UKR",
			Locale:          "uk",
			CustomerID:      "cust_444_ua",
			DeliveryService: "novaposhta",
			ShardKey:        "4",
			SmID:            95,
			DateCreated:     time.Date(2023, 6, 20, 16, 45, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Мария Коваль",
				City:    "Одесса",
				Address: "ул. Дерибасовская, д. 15",
				Region:  "Одесская область",
				Email:   "maria@example.com",
				Phone:   "+380481234567",
				Zip:     "65000",
			},
			Payment: Payment{
				Transaction:  "trans444444",
				Currency:     "UAH",
				Provider:     "privat24",
				Amount:       3500,
				PaymentDT:    time.Now().Unix(),
				Bank:         "privatbank",
				DeliveryCost: 200,
				GoodsTotal:   3300,
			},
			Items: []Item{
				{
					ChrtID:      44401,
					TrackNumber: "ITEM-44401",
					Price:       1200,
					Name:        "Платье",
					Sale:        15,
					Size:        "M",
					TotalPrice:  1020,
					NmID:        444001,
					Brand:       "FashionBrand",
					Status:      200,
				},
				{
					ChrtID:      44402,
					TrackNumber: "ITEM-44402",
					Price:       800,
					Name:        "Туфли",
					Sale:        10,
					Size:        "38",
					TotalPrice:  720,
					NmID:        444002,
					Brand:       "ShoeBrand",
					Status:      200,
				},
			},
		},
		{
			OrderUID:        "order_555_de",
			TrackNumber:     "TRACK-555-DE",
			Entry:           "DEU",
			Locale:          "de",
			CustomerID:      "cust_555_de",
			DeliveryService: "dhl",
			ShardKey:        "5",
			SmID:            100,
			DateCreated:     time.Date(2023, 7, 5, 12, 30, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Hans Müller",
				City:    "Berlin",
				Address: "Friedrichstraße 100",
				Region:  "Berlin",
				Email:   "hans@example.com",
				Phone:   "+493012345678",
				Zip:     "10117",
			},
			Payment: Payment{
				Transaction:  "trans555555",
				Currency:     "EUR",
				Provider:     "paypal",
				Amount:       8900,
				PaymentDT:    time.Now().Unix(),
				Bank:         "deutschebank",
				DeliveryCost: 900,
				GoodsTotal:   8000,
			},
			Items: []Item{
				{
					ChrtID:      55501,
					TrackNumber: "ITEM-55501",
					Price:       4000,
					Name:        "Фотоаппарат",
					Sale:        0,
					Size:        "M",
					TotalPrice:  4000,
					NmID:        555001,
					Brand:       "CameraBrand",
					Status:      200,
				},
				{
					ChrtID:      55502,
					TrackNumber: "ITEM-55502",
					Price:       2000,
					Name:        "Объектив",
					Sale:        5,
					Size:        "S",
					TotalPrice:  1900,
					NmID:        555002,
					Brand:       "LensBrand",
					Status:      200,
				},
			},
		},
		{
			OrderUID:        "order_666_fr",
			TrackNumber:     "TRACK-666-FR",
			Entry:           "FRA",
			Locale:          "fr",
			CustomerID:      "cust_666_fr",
			DeliveryService: "laposte",
			ShardKey:        "6",
			SmID:            105,
			DateCreated:     time.Date(2023, 8, 15, 14, 0, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Marie Dupont",
				City:    "Paris",
				Address: "Champs-Élysées 50",
				Region:  "Île-de-France",
				Email:   "marie@example.com",
				Phone:   "+33123456789",
				Zip:     "75008",
			},
			Payment: Payment{
				Transaction:  "trans666666",
				Currency:     "EUR",
				Provider:     "creditcard",
				Amount:       7500,
				PaymentDT:    time.Now().Unix(),
				Bank:         "societegenerale",
				DeliveryCost: 700,
				GoodsTotal:   6800,
			},
			Items: []Item{
				{
					ChrtID:      66601,
					TrackNumber: "ITEM-66601",
					Price:       2500,
					Name:        "Духи",
					Sale:        10,
					Size:        "S",
					TotalPrice:  2250,
					NmID:        666001,
					Brand:       "PerfumeBrand",
					Status:      200,
				},
				{
					ChrtID:      66602,
					TrackNumber: "ITEM-66602",
					Price:       1800,
					Name:        "Косметичка",
					Sale:        5,
					Size:        "M",
					TotalPrice:  1710,
					NmID:        666002,
					Brand:       "CosmeticBrand",
					Status:      200,
				},
			},
		},
		{
			OrderUID:        "order_777_es",
			TrackNumber:     "TRACK-777-ES",
			Entry:           "ESP",
			Locale:          "es",
			CustomerID:      "cust_777_es",
			DeliveryService: "correos",
			ShardKey:        "7",
			SmID:            110,
			DateCreated:     time.Date(2023, 9, 1, 11, 45, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Juan García",
				City:    "Madrid",
				Address: "Gran Vía 80",
				Region:  "Madrid",
				Email:   "juan@example.com",
				Phone:   "+34123456789",
				Zip:     "28013",
			},
			Payment: Payment{
				Transaction:  "trans777777",
				Currency:     "EUR",
				Provider:     "bizum",
				Amount:       4200,
				PaymentDT:    time.Now().Unix(),
				Bank:         "santander",
				DeliveryCost: 300,
				GoodsTotal:   3900,
			},
			Items: []Item{
				{
					ChrtID:      77701,
					TrackNumber: "ITEM-77701",
					Price:       1500,
					Name:        "Футболка",
					Sale:        20,
					Size:        "L",
					TotalPrice:  1200,
					NmID:        777001,
					Brand:       "ClothingBrand",
					Status:      200,
				},
				{
					ChrtID:      77702,
					TrackNumber: "ITEM-77702",
					Price:       1200,
					Name:        "Джинсы",
					Sale:        15,
					Size:        "M",
					TotalPrice:  1020,
					NmID:        777002,
					Brand:       "JeansBrand",
					Status:      200,
				},
			},
		},
		{
			OrderUID:        "order_888_it",
			TrackNumber:     "TRACK-888-IT",
			Entry:           "ITA",
			Locale:          "it",
			CustomerID:      "cust_888_it",
			DeliveryService: "posteitaliane",
			ShardKey:        "8",
			SmID:            115,
			DateCreated:     time.Date(2023, 10, 10, 9, 0, 0, 0, time.UTC),
			OofShard:        "",
			Delivery: Delivery{
				Name:    "Giuseppe Rossi",
				City:    "Roma",
				Address: "Via del Corso 200",
				Region:  "Lazio",
				Email:   "giuseppe@example.com",
				Phone:   "+390612345678",
				Zip:     "00186",
			},
			Payment: Payment{
				Transaction:  "trans888888",
				Currency:     "EUR",
				Provider:     "satispay",
				Amount:       6800,
				PaymentDT:    time.Now().Unix(),
				Bank:         "unicredit",
				DeliveryCost: 600,
				GoodsTotal:   6200,
			},
			Items: []Item{
				{
					ChrtID:      88801,
					TrackNumber: "ITEM-88801",
					Price:       3500,
					Name:        "Сумка",
					Sale:        10,
					Size:        "M",
					TotalPrice:  3150,
					NmID:        888001,
					Brand:       "BagBrand",
					Status:      200,
				},
				{
					ChrtID:      88802,
					TrackNumber: "ITEM-88802",
					Price:       1800,
					Name:        "Кошелек",
					Sale:        5,
					Size:        "S",
					TotalPrice:  1710,
					NmID:        888002,
					Brand:       "WalletBrand",
					Status:      200,
				},
			},
		},
	}

	time.Sleep(10 * time.Second)

	writer := kafka.NewWriter(kafka.WriterConfig{
		Brokers: []string{"kafka:9092"},
		Topic:   "test-topic",
	})
	defer writer.Close()

	for _, v := range orders {
		js, err := json.Marshal(v)
		if err != nil {
			panic("Ошибка при сериализации")
		}
		err = writer.WriteMessages(ctx, kafka.Message{
			Value: js,
		})
		if err != nil {
			fmt.Println("Ошибка при отправке:", err)
		}
	}
}
